#!/bin/bash

echo "================================"
echo "將 AI Monitor 整合到主專案"
echo "================================"
echo ""
echo "此腳本會幫您將 AI Monitor 功能整合到 www.qcair.us"
echo ""
echo "步驟 1: 在主專案添加 AI Monitor API"
echo "---------------------------------------"
echo "請將以下檔案複製到您的主專案："
echo ""
echo "1. app/api/ai-monitor/route.ts"
echo "2. components/AICameraGrid.tsx"
echo "3. app/ai-monitor/page.tsx"
echo ""
echo "步驟 2: 安裝必要套件"
echo "---------------------------------------"
echo "cd [您的主專案目錄]"
echo "npm install axios lucide-react"
echo ""
echo "步驟 3: 在 Railway 設定環境變數"
echo "---------------------------------------"
echo "在 sparkling-inspiration 專案的 Variables 頁面添加："
echo ""
echo "AI_MONITOR_HOST=192.168.1.184"
echo "AI_MONITOR_PORT=9001"
echo ""
echo "步驟 4: 推送並部署"
echo "---------------------------------------"
echo "git add ."
echo "git commit -m 'Add AI Monitor integration'"
echo "git push"
echo ""
echo "完成後，您可以訪問："
echo "https://www.qcair.us/ai-monitor"